# 环境变量
env:
  global:
    - TZ=Asia/Shanghai

language: node_js
node_js: node # node: 指定 Node.js 版本为 latest stable Node.js release

# 只监测 source 分支
branches:
  only:
    - source

cache:
  #  apt: true # 缓存 apt 依赖
  directories:
    - node_modules # 缓存 node_modules 目录

before_install:
  # Deploy history
  # 将上次部署的内容(master 分支的 top commit)克隆到 .deploy_git
  - git clone --branch=master --single-branch https://github.com/Gzhennaxia/Gzhennaxia.github.io.git .last_deployed_backup

install: npm install

before_script:

script:
  - hexo clean
  - hexo g

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: source
  local-dir: public # 要发布到 GitHub Pages 的目录
  target_branch: master
